### ISSUE TITLE
Not working on Paper 1.21.11

### ISSUE THREAD

**Issue by leonardo00234** [Jannyboy11/InvSee-plus-plus#183]
Last version of plugin (0.30.15) is not working on Paper 1.21.11 Build 52, it's an experimental build so it may be a paper problem and be fixed in stable versions, but it may also be due to change in mappings in 1.21.11.
The error:
`[Server thread/ERROR]: Error occurred while enabling InvSeePlusPlus v0.30.15 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/world/entity/player/EntityHuman
	at InvSee++.jar//com.janboerman.invsee.spigot.Impl_1_21_11.<init>(Setup.java:143) ~[?:?]
	at InvSee++.jar//com.janboerman.invsee.spigot.SetupImpl.lambda$static$15(Setup.java:174) ~[?:?]
	at InvSee++.jar//com.janboerman.invsee.spigot.Setup.setup(Setup.java:41) ~[?:?]
	at InvSee++.jar//com.janboerman.invsee.spigot.InvseePlusPlus.onEnable(InvseePlusPlus.java:86) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.21.11-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.11.jar:1.21.11-51-90191f7]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.11.jar:1.21.11-51-90191f7]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.11-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.21.11.jar:1.21.11-51-90191f7]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:596) ~[paper-1.21.11.jar:1.21.11-51-90191f7]
	at net.minecraft.server.MinecraftServer.initPostWorld(MinecraftServer.java:636) ~[paper-1.21.11.jar:1.21.11-51-90191f7]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:365) ~[paper-1.21.11.jar:1.21.11-51-90191f7]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[paper-1.21.11.jar:1.21.11-51-90191f7]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:388) ~[paper-1.21.11.jar:1.21.11-51-90191f7]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.entity.player.EntityHuman
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:208) ~[paper-api-1.21.11-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:175) ~[paper-api-1.21.11-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 15 more`

**Comment by srnyx** [comment]
Happening on Paper 1.21.8 too: `This server is running Paper version 1.21.8-60-main@29c8822 (2025-09-06T21:49:13Z) (Implementing API version 1.21.8-R0.1-SNAPSHOT)`

```
[13:27:53 ERROR]: Error occurred while enabling InvSeePlusPlus v0.31.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/world/entity/player/EntityHuman
at InvSee++.jar/com.janboerman.invsee.spigot.Impl_1_21_7.<init>(Setup.java:131) ~[InvSee++.jar:?]
at InvSee++.jar/com.janboerman.invsee.spigot.SetupImpl.lambda$static$13(Setup.java:178) ~[InvSee++.jar:?]
at InvSee++.jar/com.janboerman.invsee.spigot.Setup.setup(Setup.java:41) ~[InvSee++.jar:?]
at InvSee++.jar/com.janboerman.invsee.spigot.InvseePlusPlus.onEnable(InvseePlusPlus.java:86) ~[InvSee++.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280) ~[paper-api-1.21.8-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.8.jar:1.21.8-60-29c8822]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.8.jar:1.21.8-60-29c8822]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.8-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:652) ~[paper-1.21.8.jar:1.21.8-60-29c8822]
at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:608) ~[paper-1.21.8.jar:1.21.8-60-29c8822]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743) ~[paper-1.21.8.jar:1.21.8-60-29c8822]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:488) ~[paper-1.21.8.jar:1.21.8-60-29c8822]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280) ~[paper-1.21.8.jar:1.21.8-60-29c8822]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.21.8.jar:1.21.8-60-29c8822]
at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.8.jar:1.21.8-60-29c8822]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.entity.player.EntityHuman
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:205) ~[paper-api-1.21.8-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:172) ~[paper-api-1.21.8-R0.1-SNAPSHOT.jar:?]
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
... 16 more
```

**Comment by srnyx** [comment]
> [@srnyx](https://github.com/srnyx) please see [spigotmc.org/resources/invsee.82342/update?update=621237](https://www.spigotmc.org/resources/invsee.82342/update?update=621237)

~~Could the 0.31.0 Modrinth version reflect this new version compatibility to avoid further confusion? Currently, it's listed as supporting all of these versions:~~
<img width="351" height="177" alt="Image" src="https://github.com/user-attachments/assets/0895d0ae-368c-472f-accf-4d6dca04e492" />

---

Nevermind, I see the issue. It still supports Bukkit/Spigot 1.21.11-, but not Paper 1.21.11-
