### ISSUE TITLE
v0.30.10 can't work on paper-1.21.9-45.jar

### ISSUE THREAD

**Issue by xiaohuang2004** [Jannyboy11/InvSee-plus-plus#166]
When the server started, error happened 
`[14:58:53 INFO]: [InvSee++] Enabling InvSeePlusPlus v0.30.10
[14:58:53 INFO]: [InvSee++] Detected server software: Paper version 1.21.9
[14:58:53 ERROR]: Error occurred while enabling InvSeePlusPlus v0.30.10 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/world/entity/player/EntityHuman
        at InvSee++.jar/com.janboerman.invsee.spigot.Impl_1_21_9.<init>(Setup.java:149) ~[InvSee++.jar:?]
        at InvSee++.jar/com.janboerman.invsee.spigot.SetupImpl.lambda$static$16(Setup.java:181) ~[InvSee++.jar:?]
        at InvSee++.jar/com.janboerman.invsee.spigot.Setup.setup(Setup.java:41) ~[InvSee++.jar:?]
        at InvSee++.jar/com.janboerman.invsee.spigot.InvseePlusPlus.onEnable(InvseePlusPlus.java:86) ~[InvSee++.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.21.9-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.9.jar:1.21.9-45-a3f247c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.9.jar:1.21.9-45-a3f247c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.9-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.21.9.jar:1.21.9-45-a3f247c]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:595) ~[paper-1.21.9.jar:1.21.9-45-a3f247c]
        at net.minecraft.server.MinecraftServer.initPostWorld(MinecraftServer.java:554) ~[paper-1.21.9.jar:1.21.9-45-a3f247c]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:368) ~[paper-1.21.9.jar:1.21.9-45-a3f247c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1096) ~[paper-1.21.9.jar:1.21.9-45-a3f247c]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:317) ~[paper-1.21.9.jar:1.21.9-45-a3f247c]
        at java.base/java.lang.Thread.run(Thread.java:1447) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.entity.player.EntityHuman
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:208) ~[paper-api-1.21.9-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:175) ~[paper-api-1.21.9-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490) ~[?:?]
        ... 15 more
[14:58:53 INFO]: [InvSee++] Disabling InvSeePlusPlus v0.30.10
[14:58:53 ERROR]: Error occurred (in the plugin loader) while removing chunk tickets for InvSeePlusPlus v0.30.10 (Is it up to date?)
java.lang.IllegalStateException: Nullability of identifier should match nullability of comparator
        at net.minecraft.server.level.Ticket.moonrise$setIdentifier(Ticket.java:48) ~[paper-1.21.9.jar:1.21.9-45-a3f247c]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.removeTicketAtLevel(ChunkHolderManager.java:684) ~[paper-1.21.9.jar:1.21.9-45-a3f247c]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.removeAllTicketsFor(ChunkHolderManager.java:787) ~[paper-1.21.9.jar:1.21.9-45-a3f247c]
        at net.minecraft.world.level.TicketStorage.removeAllPluginRegionTickets(TicketStorage.java:341) ~[paper-1.21.9.jar:1.21.9-45-a3f247c]
        at org.bukkit.craftbukkit.CraftWorld.removePluginChunkTickets(CraftWorld.java:601) ~[paper-1.21.9.jar:1.21.9-45-a3f247c]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:316) ~[paper-1.21.9.jar:1.21.9-45-a3f247c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.9.jar:1.21.9-45-a3f247c]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-api-1.21.9-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.9.jar:1.21.9-45-a3f247c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.9.jar:1.21.9-45-a3f247c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.9-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.21.9.jar:1.21.9-45-a3f247c]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:595) ~[paper-1.21.9.jar:1.21.9-45-a3f247c]
        at net.minecraft.server.MinecraftServer.initPostWorld(MinecraftServer.java:554) ~[paper-1.21.9.jar:1.21.9-45-a3f247c]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:368) ~[paper-1.21.9.jar:1.21.9-45-a3f247c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1096) ~[paper-1.21.9.jar:1.21.9-45-a3f247c]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:317) ~[paper-1.21.9.jar:1.21.9-45-a3f247c]
        at java.base/java.lang.Thread.run(Thread.java:1447) ~[?:?]`
So the command invsee doesn't work because the plugin loaded wrongly.

**Comment by Jannyboy11** [comment]
This will be fixed in Paper once https://github.com/PaperMC/Paper/pull/13135/ is merged.
